version: "3.8"

services:
  web:
    container_name: chores-app
    build: .
    ports:
     - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
  db:
    container_name: postgres-db
    image: postgres:15.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
     - "5432:5432"




